@echo off
echo Starting Cracker Demo local development environment...
echo Waiting for server to initialize...
start "" powershell -Command "Start-Sleep -Seconds 2; Start-Process 'http://127.0.0.1:9000'"
"%~dp0.tools\php\php.exe" -c "%~dp0.tools\php\php.ini" "%~dp0artisan" serve --port=9000

